package org.example;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.PriorityQueue;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class LeaderboardGUI extends javax.swing.JFrame {
    @Autowired
    PortfolioRecordRepository portfolioRecordRepository;

    String name=null;
    String gmail=null;
    String password=null;
    String userId=null;


     public void getList(String n,String g,String p,String u, Portfolio portfolio) {
        List<PortfolioRecord> list = portfolioRecordRepository.findAll();
        PriorityQueue<Double> sort = new PriorityQueue<>(Collections.reverseOrder());
        HashMap<Double, String> alreadyContainUserID = new HashMap<>();
        // HashSet<String>userId = new HashSet<>();
        for(int i = 0; i < list.size(); i++){
            if(!alreadyContainUserID.containsKey(list.get(i).getUserID())){
                //the getOverallPoint method in Portfolio class is tocalcuate the total points for all the stocks that a user has bought
                alreadyContainUserID.put(portfolio.getOverallPoint(list.get(i).getUserID()), list.get(i).getUserID());
                sort.add(list.get(i).getOverallPoint());
            }
            // userId.add(list.get(i).getUserID());
        }
        while(!sort.isEmpty()){
            for (Map.Entry<Double, String> entry : alreadyContainUserID.entrySet()) {
                double point = sort.peek();
                if(point == entry.getKey()){
                    //display in the leaderboard
                    System.out.println(entry.getValue() + ": " + point);
                    sort.poll();
                }
            }
        }
     
        
        name = n;
        gmail = g;
        password = p;
        userId = u;

        name1.setText("a");
        name2.setText("b");
        name3.setText("c");
        name4.setText("d");
        name5.setText("e");
        name6.setText("f");
        name7.setText("g");
        name8.setText("g");
        name9.setText("h");
        name10.setText("i");

        points1.setText("1");
        points2.setText("2");
        points3.setText("3");
        points4.setText("4");
        points5.setText("5");
        points6.setText("6");
        points7.setText("7");
        points8.setText("8");
        points9.setText("9");
        points10.setText("10");
        
    }

    public LeaderboardGUI() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        name3 = new javax.swing.JTextField();
        name4 = new javax.swing.JTextField();
        name5 = new javax.swing.JTextField();
        name6 = new javax.swing.JTextField();
        name7 = new javax.swing.JTextField();
        name8 = new javax.swing.JTextField();
        name9 = new javax.swing.JTextField();
        name10 = new javax.swing.JTextField();
        points1 = new javax.swing.JTextField();
        points2 = new javax.swing.JTextField();
        points3 = new javax.swing.JTextField();
        points4 = new javax.swing.JTextField();
        points5 = new javax.swing.JTextField();
        points6 = new javax.swing.JTextField();
        points7 = new javax.swing.JTextField();
        points8 = new javax.swing.JTextField();
        points9 = new javax.swing.JTextField();
        points10 = new javax.swing.JTextField();
        jButtonExit = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(137, 196, 244));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\natas\\Pictures\\winner.png")); // NOI18N
        jLabel1.setText("   Leaderboard");

        jPanel2.setBackground(new java.awt.Color(212, 250, 252));

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.setText("UserID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ranking");

        PL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PL.setText("P/L");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("1");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("2");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("3");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("4");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("5");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("6");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("7");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("8");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("9");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("10");

        name1.setBackground(new java.awt.Color(212, 250, 252));
        name1.setCaretColor(new java.awt.Color(255, 255, 255));
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });

        name2.setBackground(new java.awt.Color(212, 250, 252));
        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2ActionPerformed(evt);
            }
        });

        name3.setBackground(new java.awt.Color(212, 250, 252));
        name3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name3ActionPerformed(evt);
            }
        });

        name4.setBackground(new java.awt.Color(212, 250, 252));
        name4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name4ActionPerformed(evt);
            }
        });

        name5.setBackground(new java.awt.Color(212, 250, 252));
        name5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name5ActionPerformed(evt);
            }
        });

        name6.setBackground(new java.awt.Color(212, 250, 252));
        name6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name6ActionPerformed(evt);
            }
        });

        name7.setBackground(new java.awt.Color(212, 250, 252));
        name7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name7ActionPerformed(evt);
            }
        });

        name8.setBackground(new java.awt.Color(212, 250, 252));
        name8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name8ActionPerformed(evt);
            }
        });

        name9.setBackground(new java.awt.Color(212, 250, 252));
        name9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name9ActionPerformed(evt);
            }
        });

        name10.setBackground(new java.awt.Color(212, 250, 252));
        name10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name10ActionPerformed(evt);
            }
        });

        points1.setBackground(new java.awt.Color(212, 250, 252));
        points1.setCaretColor(new java.awt.Color(255, 255, 255));
        points1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                points1ActionPerformed(evt);
            }
        });

        points2.setBackground(new java.awt.Color(212, 250, 252));
        points2.setCaretColor(new java.awt.Color(255, 255, 255));
        points2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                points2ActionPerformed(evt);
            }
        });

        points3.setBackground(new java.awt.Color(212, 250, 252));
        points3.setCaretColor(new java.awt.Color(255, 255, 255));
        points3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                points3ActionPerformed(evt);
            }
        });

        points4.setBackground(new java.awt.Color(212, 250, 252));
        points4.setCaretColor(new java.awt.Color(255, 255, 255));
        points4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                points4ActionPerformed(evt);
            }
        });

        points5.setBackground(new java.awt.Color(212, 250, 252));
        points5.setCaretColor(new java.awt.Color(255, 255, 255));
        points5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                points5ActionPerformed(evt);
            }
        });

        points6.setBackground(new java.awt.Color(212, 250, 252));
        points6.setCaretColor(new java.awt.Color(255, 255, 255));
        points6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                points6ActionPerformed(evt);
            }
        });

        points7.setBackground(new java.awt.Color(212, 250, 252));
        points7.setCaretColor(new java.awt.Color(255, 255, 255));
        points7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                points7ActionPerformed(evt);
            }
        });

        points8.setBackground(new java.awt.Color(212, 250, 252));
        points8.setCaretColor(new java.awt.Color(255, 255, 255));
        points8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                points8ActionPerformed(evt);
            }
        });

        points9.setBackground(new java.awt.Color(212, 250, 252));
        points9.setCaretColor(new java.awt.Color(255, 255, 255));
        points9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                points9ActionPerformed(evt);
            }
        });

        points10.setBackground(new java.awt.Color(212, 250, 252));
        points10.setCaretColor(new java.awt.Color(255, 255, 255));
        points10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                points10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(jLabel7,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 19,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel5,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel6,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addGroup(jPanel2Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(jLabel13,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 23,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel12,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel11,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel10,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(name9, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(name8, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(name7, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(name6, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(name5, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(name4, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(name3, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(name2, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(name1, javax.swing.GroupLayout.DEFAULT_SIZE, 115,
                                                                Short.MAX_VALUE)
                                                        .addComponent(name10)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(points1, javax.swing.GroupLayout.DEFAULT_SIZE, 94,
                                                                Short.MAX_VALUE)
                                                        .addComponent(points2)
                                                        .addComponent(points3)
                                                        .addComponent(points4)
                                                        .addComponent(points5)
                                                        .addComponent(points6)
                                                        .addComponent(points7)
                                                        .addComponent(points8)
                                                        .addComponent(points9)
                                                        .addComponent(points10))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(PL)
                                                .addGap(54, 54, 54)))));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(PL)
                                        .addComponent(Name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(points1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(points2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(points3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(name4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(points4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(name5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(points5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(name6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(points6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(name7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(points7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(name8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(points8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(name9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(points9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(name10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(points10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)));

        jButtonExit.setBackground(new java.awt.Color(205, 24, 24));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExit.setText("BACK");
        jButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExitMouseClicked(evt);
                try {
                    MainClass.method(name, gmail, userId, password);
                } catch (Exception e) { e.printStackTrace(); }
            }
        });
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71,
                                        Short.MAX_VALUE)
                                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 88,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonExit)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_name1ActionPerformed

    private void name2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_name2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_name2ActionPerformed

    private void name3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_name3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_name3ActionPerformed

    private void name4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_name4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_name4ActionPerformed

    private void name5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_name5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_name5ActionPerformed

    private void name6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_name6ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_name6ActionPerformed

    private void name7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_name7ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_name7ActionPerformed

    private void name8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_name8ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_name8ActionPerformed

    private void name9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_name9ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_name9ActionPerformed

    private void name10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_name10ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_name10ActionPerformed

    private void points1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_points1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_points1ActionPerformed

    private void points2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_points2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_points2ActionPerformed

    private void points3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_points3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_points3ActionPerformed

    private void points4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_points4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_points4ActionPerformed

    private void points5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_points5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_points5ActionPerformed

    private void points6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_points6ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_points6ActionPerformed

    private void points7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_points7ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_points7ActionPerformed

    private void points8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_points8ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_points8ActionPerformed

    private void points9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_points9ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_points9ActionPerformed

    private void points10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_points10ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_points10ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonExitActionPerformed

    }

    private void jButtonExitMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonExitMouseClicked
        this.dispose();
        // System.exit(0);
    }// GEN-LAST:event_jButtonExitMouseClicked

    // public static void main(String args[]) {

    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(LeaderboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
    //                 ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(LeaderboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
    //                 ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(LeaderboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
    //                 ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(LeaderboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
    //                 ex);
    //     }
    //     // </editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new LeaderboardGUI().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel PL;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name10;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField name3;
    private javax.swing.JTextField name4;
    private javax.swing.JTextField name5;
    private javax.swing.JTextField name6;
    private javax.swing.JTextField name7;
    private javax.swing.JTextField name8;
    private javax.swing.JTextField name9;
    private javax.swing.JTextField points1;
    private javax.swing.JTextField points10;
    private javax.swing.JTextField points2;
    private javax.swing.JTextField points3;
    private javax.swing.JTextField points4;
    private javax.swing.JTextField points5;
    private javax.swing.JTextField points6;
    private javax.swing.JTextField points7;
    private javax.swing.JTextField points8;
    private javax.swing.JTextField points9;

    //private void bubbleSort(ArrayList);
}
