package org.example;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import org.apache.catalina.UserDatabase;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Service;

import ch.qos.logback.core.boolex.Matcher;

import java.awt.*;
import java.io.*;
import java.util.Random;
import java.util.regex.Pattern;

// @SpringBootApplication
@Service
public class RegisterForm extends javax.swing.JFrame {
    @Autowired
    UserRepository userRepository;

    private String userID;
    private String password;
    private String firstName;
    private String lastName;
    private String emailAddress;
    private String confirmPassword;

    User user = new User();

    boolean otpSent = false;
    int randomNumber = 0;

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        FirstName = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        pswrd = new javax.swing.JPasswordField();
        jButtonClear = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jLabelRegister = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();

        otp = new javax.swing.JTextField();
        otpLabel = new javax.swing.JLabel();

        UserID = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        EmailAddress = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JLabel();
        conpswrd = new javax.swing.JPasswordField();
        eaddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        // getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(137, 196, 244));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registeration");

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255,
                                        Short.MAX_VALUE)
                                .addComponent(jLabelMin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelClose)
                                .addGap(26, 26, 26)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelClose, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelMin, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(19, 19, 19)));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 60);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        // getContentPane().add(jTextField1);
        jTextField1.setBounds(0, 0, 7, 23);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        // getContentPane().add(jTextField2);
        jTextField2.setBounds(0, 0, 7, 23);

        jPanel2.setBackground(new java.awt.Color(197, 239, 247));

        FirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FirstName.setText("First Name:");

        Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password.setText("Password:");

        uid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });

        pswrd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswrdActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(205, 24, 24));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonRegister.setBackground(new java.awt.Color(149, 189, 255));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegister.setText("Register/Send OTP");

        //jButtonRegister.setText("allah");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jLabelRegister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRegister.setText("Click here to login");
        jLabelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
        });

        fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        UserID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserID.setText("UserID:");

        LastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LastName.setText("Last Name:");

        // Look here
        otpLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        otpLabel.setText("OTP:");

        otp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpActionPerformed(evt);
            }
        });

        lname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });

        EmailAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmailAddress.setText("Email Address:");

        ConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ConfirmPassword.setText("Confirm Password:");

        conpswrd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        conpswrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpswrdActionPerformed(evt);
            }
        });

        eaddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(EmailAddress)
                                                        .addComponent(LastName)
                                                        .addComponent(FirstName)
                                                        .addComponent(UserID, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Password)
                                                        .addComponent(ConfirmPassword)
                                                        .addComponent(otpLabel))
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(conpswrd, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(lname,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 197,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(fname,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 197,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(eaddress,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 197,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(uid,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 197,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(pswrd,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 197,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(otp,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 197,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 111,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonRegister,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        (int) jButtonRegister.getPreferredSize().getWidth(),
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 27, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabelRegister)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                // .addGap(26, 26, 26)
                                .addGap(100, 100, 100)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FirstName))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LastName))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(EmailAddress)
                                        .addComponent(eaddress, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(UserID)
                                        .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Password)
                                        .addComponent(pswrd, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ConfirmPassword)
                                        .addComponent(conpswrd, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(otpLabel)
                                        .addComponent(otp, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(jLabelRegister)
                                .addContainerGap(41, Short.MAX_VALUE)));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-3, 60, 430, 530);

        // setMinimumSize(new Dimension(800, 600));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }// GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }// GEN-LAST:event_jLabelMinMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField2ActionPerformed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_uidActionPerformed

    private void pswrdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pswrdActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_pswrdActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonClearActionPerformed
        fname.setText(null);
        lname.setText(null);
        eaddress.setText(null);
        uid.setText(null);
        pswrd.setText(null);
        conpswrd.setText(null);
        otp.setText(null);
    }// GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRegisterActionPerformed
        String FirstName = fname.getText().toString();
        String OTP = otp.getText().toString();
        String LastName = lname.getText().toString();
        String EmailAddress = eaddress.getText().toString();
        String UserID = uid.getText().toString();
        String Password = pswrd.getText().toString();
        String ConfirmPassword = conpswrd.getText().toString();

        // Assign the input values to the instance variables
        user.setFirstName(FirstName);
        user.setLastName(LastName);
        user.setEmailAddress(EmailAddress);
        user.setUserID(UserID);
        user.setPassword(Password);
        user.setConfirmPassword(ConfirmPassword);

        if (FirstName.equals("")) {
            JOptionPane.showMessageDialog(null, "First Name is Mandatory.");
            return;
        }
        if (LastName.equals("")) {
            JOptionPane.showMessageDialog(null, "Last Name is Mandatory.");
            return;
        }
        if (EmailAddress.equals("")) {
            JOptionPane.showMessageDialog(null, "Email Address is Mandatory.");
            return;
        }

        String gmailPattern = "\\b[A-Za-z0-9._%+-]+@gmail\\.com\\b";
        String siswaPattern = "\\b[A-Za-z0-9._%+-]+@siswa\\.um\\.edu\\.my\\b";

        Pattern patternGmail = Pattern.compile(gmailPattern);
        Pattern patternSiswa = Pattern.compile(siswaPattern);

        java.util.regex.Matcher matcherGmail = patternGmail.matcher(EmailAddress);
        java.util.regex.Matcher matcherSiswa = patternSiswa.matcher(EmailAddress);

        boolean isGmailAddress = matcherGmail.matches();
        boolean isSiswa = matcherSiswa.matches();

        if (!isSiswa && !isGmailAddress) {
            JOptionPane.showMessageDialog(null, "Invalid Email Address");
            return;
        }
        if (UserID.equals("")) {
            JOptionPane.showMessageDialog(null, "UserID is Mandatory.");
            return;
        }

        java.util.List<userDatabase>list = Global.getApplicationContext().getBean(LoginForm.class).userRepository.findAll();
        
        for(int i=0;i<list.size();i++){
            if(list.get(i).getUserID().equals(UserID)){
                JOptionPane.showMessageDialog(null, "This UserID is being utilized by another user");
                return;
            }
        }
        
        if (Password.equals("")) {
            JOptionPane.showMessageDialog(null, "Password is Mandatory.");
            return;
        }
        if (ConfirmPassword.equals("")) {
            JOptionPane.showMessageDialog(null, "Confirm Password is Mandatory.");
            return;
        }
        if (!Password.equals(ConfirmPassword)) {
            JOptionPane.showMessageDialog(null, "The password and confirmed password must match.");
            return;
        }



        if (!otpSent) {
            // Create an instance of Random
            Random random = new Random();

            // Generate a random 6-digit number
            randomNumber = random.nextInt(900000) + 100000;

            new SendEmail();
            SendEmail.sendAnEmail(EmailAddress, "Gmail Verification",
                    ("OTP - " + randomNumber + " is your verification"));
            otpSent = true;
            JOptionPane.showMessageDialog(null, "One-Time Password (OTP) has been dispatched to your email address");
        } else {
            System.out.println(OTP);
            System.out.println(randomNumber);
            if (!OTP.equals(Integer.toString(randomNumber))) {
                JOptionPane.showMessageDialog(null, "Incorrect OTP.");
            } else {
                JOptionPane.showMessageDialog(null, "Validation succesful");
                userDatabase database2 = new userDatabase();

                System.out.println("First Name: " + user.getFirstName());
                System.out.println("Last Name: " + user.getLastName());
                System.out.println("Email Address: " + user.getEmailAddress());
                System.out.println("UserID: " + user.getUserID());
                System.out.println("Password: " + user.getPassword());
                System.out.println("Confirm Password: " + user.getConfirmPassword());

                database2.setFirstName(user.getFirstName());
                database2.setLastName(user.getLastName());
                database2.setGmail(user.getEmailAddress());
                database2.setUserID(user.getUserID());
                database2.setPassword(user.getPassword());
                Global.getApplicationContext().getBean(RegisterForm.class).userRepository.save(database2);
            }
        }

        // if (!OTP.equals(Integer.toString(randomNumber))) {
        //     JOptionPane.showMessageDialog(null, "Incorrect OTP.");
        //     return;
        // } else {
        //     JOptionPane.showMessageDialog(null, "Validation succesful");
        //     userDatabase database2 = new userDatabase();

        //     System.out.println("First Name: " + user.getFirstName());
        //     System.out.println("Last Name: " + user.getLastName());
        //     System.out.println("Email Address: " + user.getEmailAddress());
        //     System.out.println("UserID: " + user.getUserID());
        //     System.out.println("Password: " + user.getPassword());
        //     System.out.println("Confirm Password: " + user.getConfirmPassword());

        //     database2.setFirstName(user.getFirstName());
        //     database2.setLastName(user.getLastName());
        //     database2.setGmail(user.getEmailAddress());
        //     database2.setUserID(user.getUserID());
        //     database2.setPassword(user.getPassword());
        //     Global.getApplicationContext().getBean(RegisterForm.class).userRepository.save(database2);

    } // GEN-LAST:event_jButtonRegisterActionPerformed


    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fnameActionPerformed
        String firstName = "";
    }// GEN-LAST:event_fnameActionPerformed

    private void otpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fnameActionPerformed
        String otp = "";
    }// GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lnameActionPerformed
        String lastName = "";
    }// GEN-LAST:event_lnameActionPerformed

    private void conpswrdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_conpswrdActionPerformed
        String ConfirmPassword = "";
    }// GEN-LAST:event_conpswrdActionPerformed

    private void eaddressActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_eaddressActionPerformed
        String EmailAddress = "";
    }// GEN-LAST:event_eaddressActionPerformed

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabelRegisterMouseClicked
        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.pack();
        lgf.setLocationRelativeTo(null);
        lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmPassword;
    private javax.swing.JLabel EmailAddress;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel UserID;
    private javax.swing.JPasswordField conpswrd;
    private javax.swing.JTextField eaddress;
    private javax.swing.JTextField fname;

    private javax.swing.JTextField otp;
    private JLabel otpLabel;

    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField pswrd;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
